---
title: "Code"
---

Looking for R packages for multivariate time-series analysis ([MARSS](https://nwfsc-timeseries.github.io/MARSS/), atsar, ...)? Head to our 
[NWFSC Time Series](https://nwfsc-timeseries.github.io/) page.  Packages, course webpage and Applied Time-Series Analysis book is there.

Looking for the "Fish Forecast" webpage?  Fish Forecast [webpage and course lectures](https://fish-forecast.github.io/Fish-Forecast-Webpage/), [online book](https://fish-forecast.github.io/Fish-Forecast-Bookdown/), [GitHub](https://github.com/fish-forecast)

Looking for the "RVerse Tutorials" material?  RVerse Tutorials [course webpage](https://rverse-tutorials.github.io/RWorkflow-Workshop/), [GitHub](https://github.com/RVerse-Tutorials)

Other random stuff is on my [GitHub](https://github.com/eeholmes) page.  However, if you are looking for time-series analysis or hierarchical modeling code, then you should look at my [colleagues](https://eeholmes.github.io/colleagues/)' GitHub repositories and project pages.

## Other code

### [fbRanks](http://cran.r-project.org/web/packages/fbRanks/index.html)
Fitting huge poission regression models using glmnet.

### [LAMBDA](https://conserver.iugo-cafe.org/user/e2holmes/LAMBDA)
A matlab package for fitting MAR(1) models. 

### [MAR1](https://CRAN.R-project.org/package=MAR1)
An R package for fitting MAR(1) models.  

### [FishBox](http://fishbox.iugo-cafe.org/) and [EcologyBox](http://conserver.iugo-cafe.org/)
Code repositories with a variety of older projects.  We have switched over to GitHub since 2012 or so.  We developed the code base that runs the repository itself as part of the Iugo-Cafe project in the 2000s.

### [iugo-cafe](http://iugo-cafe.org/)
Iugo-Cafe was an early project on development of fluid content managers for science purposes.

<!-- List all repositories
{% for repository in site.github.public_repositories %}
  * [{{ repository.name }}]({{ repository.html_url }})
{% endfor %}
-->